project:
  type: website
  output-dir: docs

website:
  title: "Jean-LucCollette.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - MiniProject1.qmd
      - Miniproject2.qmd
      - GlobalSemester.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

