---
title: "Campus Activities"
---

Here is what I am involved in on Campus and Life!

## U.S. Bank Specialty Credit Analyst

Currently I am working part-time for U.S. Bank in their Specialty CRE department. This sector deals with financial analysis of large corporate companies that invest in Real Estate properties. These companies are designated as REITs (Real Estate Investment Trusts), REOCs (Real Estate Operating Companies), and Mutual Funds. We conduct quarterly analyses of legal agreements to underwrite their ability to pay off loans

## Norseman Band

Norseman Band is St. Olaf's second performing concert band and I play percussion in the ensemble. I was treasurer of the band in my Junior year but had to step down due to my study abroad in the fall. The band consists of mostly sophomores and freshman but gives a space for many non-major musicians to practice for fun. 

Here is a link for our [last concert](https://www.stolaf.edu/multimedia/play/?e=5016). Our next concert is on May 3rd at 7:30 PM in Boe Chapel!

## SGA Deputy Secretary of Finance

In Senior year, I got appointed as the deputy secretary of finance for two SGA branches. My role is to help plan events, keep budgets, and help the organization reconcile credit card transactions. 

### Involvement Board

Involvement Board is the main branch that gives funding to clubs on campus so that they can plan events, fund large costs, and make St. Olaf a fun place to enjoy with friends. We recently had a scavenger hunt where clubs went all over campus to find things like the turtle shell on holland or the Giant Green sunglasses in CAD. We asked clubs to take photos of all the wooden doors on campus and 555 photos were submitted!

### Student Affairs Committee

Student Affairs is the main way that students communicate with the Board of Regents. Our main role is to serve as a student voice that advocates to the BoR in a concise manner. We also do student studies to see if their concerns are being heard and what things we can do to make St. Olaf a better place. Some of our initiatives include the textbook project and the new swingset coming to campus!

## Vice President of Finance Club

For Finance Club, we give a space for students with a finance emphasis in economics to explore careers, learn about events in finance, and overall try to understand what it means to be in a finance career. I have explored multiple roles in Banking and have been working for U.S. Bank in various credit-related fields for the last 3 summers. 

## Treasurer of Board Game Club

I am a huge fan of board games and I have led a club that meets every week for the past 4 years just to play board games! We average about 25 members each week (ranging from 20 to 40 on a good week) and bring almost 100 games each week to pick from. My favorites are Monopoly (even though I got banned from playing it), One night werewolf, and Ticket to Ride. 

## 2024 Ole Cup

In spring of 2024 I participated in the Ole cup with some friends I created a venture with in New Zealand. We didn't win any money, but we had a great time creating a potential business together and learned how entrepreneurship works in practice

Here is a link to the [2024 Ole Cup.](https://www.stolaf.edu/multimedia/play/?e=4703) Click through to watch me present!

## Reading

Lately I have been trying to read a lot more, especially at night before bed. Some of the books I have read this year are the new Hunger Games book, the first 4 books of the Harry Potter Series, Flowers for Algernon, and Atomic Habits. 


